services:
  # Backend service
  - type: web
    name: sharenear-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    
  # Frontend service  
  - type: web
    name: sharenear-frontend
    env: static
    plan: free
    buildCommand: npm run install-client && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_SERVER_URL
        fromService:
          type: web
          name: sharenear-backend
          property: host